import Head from 'next/head';
import Footer from './Footer';
import Navbar from './Navbar';

const Layout = ({ children }) => {
    return (

        <>
            <Head>
                <title>Game Of Thrones</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
            <Navbar />
            <section>
                {children}
            </section>
            <Footer />

        </>
    )
}

export default Layout;
