import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { db, authentication } from '../firebase/firebase-config'
import { getStorage, ref, getDownloadURL } from "firebase/storage";
import { useEffect, useState } from 'react';
import { datas } from '../data/game_of_throne'
import { collection, getDocs, setDoc, doc, getDoc, updateDoc } from "firebase/firestore";
import uuid from 'react-uuid';
import Charactor from '../components/Charactor';

export default function Home() {
  const [logo, setLogo] = useState(null);
  const [movieList, setMovieList] = useState(null);
  const logoAdd = 'gs://movie--coments.appspot.com/Logo_Game_of_Thrones.png';
  const collection_name = 'gameOT';


  const fetchImageUrl = (ImageLink, setImage) => {
    const storage = getStorage();
    getDownloadURL(ref(storage, ImageLink))
      .then((url) => {
        setImage(url)
      })
  }

  const addNewCharactorToDb = async (charactor) => {
    await setDoc(doc(db, collection_name, charactor.firstName+charactor.lastName),
      {
        id: charactor.id,
        firstName: charactor.firstName,
        lastName: charactor.lastName,
        fullName: charactor.fullName,
        title: charactor.title,
        family: charactor.family,
        image: charactor.image,
        imageUrl: charactor.imageUrl,
        likes: 0,
        dislikes: 0,
        comments: [],
      })
  }

  const asyncGetAllCollection = async () => {
    const movie_collection = collection(db,collection_name);
    const movie_snapshot = await getDocs(movie_collection);
    const movie_list = movie_snapshot.docs.map(doc => doc.data());

    console.log(movie_list);
    setMovieList (movie_list);
  }

  fetchImageUrl(logoAdd, setLogo);

  
  useEffect(() => {
      
    //datas.map(data => addNewCharactorToDb(data));
    //addNewCharactorToDb(datas[2]);
    asyncGetAllCollection();
   
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {logo && <img className={styles.logoGT} src={logo} />}
        <btn className={styles.btn}>Upload one charactor</btn>
        {movieList && <Charactor charactor = {movieList[Math.floor(Math.random()*53)]}/>}
      </main>



      {/* <iframe width="640" height="360" src="https://www.youtube.com/embed/giYeaKsXnsI" title="Game of Thrones Season 7: Official Trailer (HBO)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
